name: SharePoint File Trigger
on:
  repository_dispatch:
    types: [sharepoint_file_added]
  workflow_dispatch:

jobs:
  process-file:
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          if (Test-Path whisper-transcript) {
            Remove-Item -Recurse -Force whisper-transcript
          }
        shell: powershell

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup WSL environment
        run: |
          wsl.exe -d Ubuntu-22.04 bash -c "sudo apt-get update && sudo apt-get install -y python3 python3-pip ffmpeg"
        shell: powershell

      - name: Install dependencies in WSL
        run: |
          wsl.exe -d Ubuntu-22.04 bash -c "cd $PWD && pip3 install -r requirements.txt"
        shell: powershell

      - name: Process SharePoint file in WSL
        env:
          SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
          SHAREPOINT_TENANT_ID: ${{ secrets.SHAREPOINT_TENANT_ID }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SHAREPOINT_NAME_FILE: ${{ github.event.client_payload.NameFile }}
          SHAREPOINT_NAME_FILE_EXTENSION: ${{ github.event.client_payload.NameFileExtension }}
          SHAREPOINT_LINK: ${{ github.event.client_payload.Link }}
        run: |
          wsl.exe -d Ubuntu-22.04 bash -c "cd $PWD && 
            export SHAREPOINT_CLIENT_ID='$env:SHAREPOINT_CLIENT_ID' && 
            export SHAREPOINT_CLIENT_SECRET='$env:SHAREPOINT_CLIENT_SECRET' && 
            export SHAREPOINT_TENANT_ID='$env:SHAREPOINT_TENANT_ID' && 
            export ANTHROPIC_API_KEY='$env:ANTHROPIC_API_KEY' && 
            export SHAREPOINT_LINK='$env:SHAREPOINT_LINK' && 
            export SHAREPOINT_NAME_FILE='$env:SHAREPOINT_NAME_FILE' && 
            export SHAREPOINT_NAME_FILE_EXTENSION='$env:SHAREPOINT_NAME_FILE_EXTENSION' && 
            python3 main.py '$env:SHAREPOINT_NAME_FILE' '$env:SHAREPOINT_LINK'"
        shell: powershell