name: SharePoint File Trigger
on:
  repository_dispatch:
    types: [sharepoint_file_added]
  workflow_dispatch:
jobs:
  process-file:
    runs-on: self-hosted  # Runner auto-hospedado en Windows
    env:
      ACTIONS_STEP_DEBUG: true  # Habilita logs detallados para depuración
    steps:
      - name: Create workspace directory
        run: |
          if not exist downloads mkdir downloads
        shell: cmd
      - name: Checkout code
        uses: actions/checkout@v4  # Actualizado a v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          check-latest: true
      - name: Test Python
        run: |
          python --version
          pip list
        shell: cmd
      - name: Test System Info
        run: |
          systeminfo
          nvidia-smi 2>nul || echo "nvidia-smi no está disponible. Verifica que CUDA esté instalado."
        shell: cmd
      - name: Install FFmpeg
        run: |
          where ffmpeg >nul 2>&1
          if %errorlevel% neq 0 (
            echo Comprobando FFmpeg...
            if exist "C:\ffmpeg\ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe" (
              echo FFmpeg ya instalado, omitiendo descarga.
            ) else (
              echo Descargando e instalando FFmpeg...
              curl -L "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip" -o ffmpeg.zip
              if not exist "C:\ffmpeg" mkdir "C:\ffmpeg"
              tar -xf ffmpeg.zip -C "C:\ffmpeg"
            )
            set "PATH=%PATH%;C:\ffmpeg\ffmpeg-master-latest-win64-gpl\bin"
            echo PATH actualizado para el proceso actual
          )
          ffmpeg -version
        shell: cmd
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd
      - name: Clean downloads directory
        run: |
          if exist downloads rmdir /s /q downloads
          mkdir downloads
        shell: cmd
      - name: Process SharePoint file
        env:
          SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
          SHAREPOINT_TENANT_ID: ${{ secrets.SHAREPOINT_TENANT_ID }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SHAREPOINT_NAME_FILE: ${{ github.event.client_payload.NameFile }}
          SHAREPOINT_NAME_FILE_EXTENSION: ${{ github.event.client_payload.NameFileExtension }}
          SHAREPOINT_LINK: ${{ github.event.client_payload.Link }}
        run: |
          echo Nuevo archivo detectado:
          echo Link: %SHAREPOINT_LINK%
          echo NameFileExtension: %SHAREPOINT_NAME_FILE_EXTENSION%
          python main.py "%SHAREPOINT_NAME_FILE%" "%SHAREPOINT_LINK%"
        shell: cmd