name: SharePoint File Trigger
on:
  repository_dispatch:
    types: [sharepoint_file_added]

jobs:
  process-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Process SharePoint file
        run: |
          echo "Nuevo archivo detectado:"
          echo "Owner: ${{ body.client_payload.Link }}"
          # Aquí puedes agregar los comandos específicos que necesites ejecutar
