name: SharePoint File Trigger
on:
  repository_dispatch:
    types: [sharepoint_file_added]

jobs:
  process-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Process SharePoint file
        env:
          SHAREPOINT_NAME_FILE: ${{ github.event.client_payload.NameFile }}
          SHAREPOINT_NAME_FILE_EXTENSION: ${{ github.event.client_payload.NameFileExtension }}
          SHAREPOINT_LINK: ${{ github.event.client_payload.Link }}
        run: |
          echo "Nuevo archivo detectado:"
          echo "OwnerRepo: ${{ github.event.repositoryOwner }}"
          echo "NameRepo: ${{ github.event.repositoryName }}"
          echo "Link: ${{ github.event.client_payload.Link }}"
          echo "NameFile: ${{ github.event.client_payload.NameFile }}"
          echo "NameFileExtension: ${{ github.event.client_payload.NameFileExtension }}"

          python your_script.py "$SHAREPOINT_NAME_FILE" "$SHAREPOINT_NAME_FILE_EXTENSION" "$SHAREPOINT_LINK"