name: SharePoint File Trigger
on:
  repository_dispatch:
    types: [sharepoint_file_added]
  workflow_dispatch:

jobs:
  process-file:
    runs-on: self-hosted
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Clean workspace
        run: Remove-Item -Recurse -Force whisper-transcript -ErrorAction SilentlyContinue
        shell: powershell

      - name: Setup Environment
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          check-latest: true

      - name: Setup FFmpeg
        run: |
          $ffmpegPath = "C:\ffmpeg\ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe"
          if (-not (Test-Path $ffmpegPath)) {
            Invoke-WebRequest -Uri "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip" -OutFile "ffmpeg.zip"
            Expand-Archive -Path "ffmpeg.zip" -DestinationPath "C:\ffmpeg" -Force
          }
          $env:Path += ";C:\ffmpeg\ffmpeg-master-latest-win64-gpl\bin"
        shell: powershell

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: powershell

      - name: Prepare Downloads Directory
        run: |
          Remove-Item -Recurse -Force downloads -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path downloads
        shell: powershell

      - name: Process File
        env:
          SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
          SHAREPOINT_TENANT_ID: ${{ secrets.SHAREPOINT_TENANT_ID }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SHAREPOINT_NAME_FILE: ${{ github.event.client_payload.NameFile }}
          SHAREPOINT_NAME_FILE_EXTENSION: ${{ github.event.client_payload.NameFileExtension }}
          SHAREPOINT_LINK: ${{ github.event.client_payload.Link }}
        run: python main.py "$env:SHAREPOINT_NAME_FILE" "$env:SHAREPOINT_LINK"
        shell: powershell